#!/usr/bin/env python3
"""Generate Pitagorin's static localized pages.

English remains the editorial source at the website root. The four translated
locales are generated from reviewed, structured copy below so every route is
crawlable without JavaScript.
"""

from __future__ import annotations

import html
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "website"
BASE_URL = "https://lorenzovillarroel90.github.io/Pitagorin-website"
APP_ID = "6756659468"
PAGES = ("index", "features", "screenshots", "parents", "faq", "privacy")

LANGUAGES = {
    "en": {"name": "English", "store": "gb"},
    "es": {"name": "Español", "store": "es"},
    "de": {"name": "Deutsch", "store": "de"},
    "fr": {"name": "Français", "store": "fr"},
    "it": {"name": "Italiano", "store": "it"},
}

# These product names mirror the current iOS Localizable.strings values. The
# generator fails if translated website copy drifts away from the app labels.
APP_TERMS = {
    "es": ("Desafío de Velocidad", "Modo Aprendizaje", "La Academia", "Tablas de Multiplicar", "Repaso inteligente", "Sprint de fluidez"),
    "de": ("Blitz-Challenge", "Lernmodus", "Die Akademie", "Einmaleins", "Intelligente Wiederholung", "Flüssigkeits-Sprint"),
    "fr": ("Défi Vitesse", "Mode Apprentissage", "L’Académie", "Tables de multiplication", "Révision intelligente", "Sprint de fluidité"),
    "it": ("Sfida Velocità", "Modalità Studio", "L’Accademia", "Tabelline", "Ripasso intelligente", "Sprint di scioltezza"),
}


COPY = {
    "es": {
        "common": {
            "skip": "Saltar al contenido", "primary": "Navegación principal",
            "home": "Inicio de Pitagorin", "features": "Funciones",
            "screenshots": "La app", "families": "Para familias", "faq": "Preguntas",
            "privacy": "Privacidad", "get": "Descargar", "menu": "Menú",
            "terms": "Condiciones", "footer_nav": "Navegación del pie de página",
            "footer": "Práctica matemática lúdica y guiada para niños, familias y personas que quieren seguir aprendiendo.",
            "available": "Pitagorin. Disponible en el App Store.",
            "store": "Abrir el App Store", "all_features": "Explorar todas las funciones",
        },
        "index": {
            "title": "Pitagorin: app de matemáticas | Juegos, tablas y álgebra",
            "description": "Gana confianza con juegos de cálculo, tablas de multiplicar, tutoriales visuales y álgebra guiada en iPhone y iPad. Para niños de 5 a 13 años y adultos.",
            "og": "Pitagorin: practicar matemáticas jugando",
            "hero_kicker": "Práctica matemática que apetece empezar",
            "hero_title": "Comprende. Practica. Hazlo tuyo.",
            "hero_text": "Pitagorin convierte la aritmética, las tablas y el álgebra inicial en sesiones breves con explicaciones claras. Está pensado para niños de 5 a 13 años y también para adultos que quieren refrescar las matemáticas cotidianas.",
            "download": "Descargar gratis en el App Store", "explore": "Explorar los modos de aprendizaje",
            "device": "Disponible para iPhone y iPad",
            "proof": [("De 5 a 13 años", "Bases adaptadas a la edad"), ("También para adultos", "Repasos rápidos"), ("iPhone + iPad", "iOS 18 o posterior"), ("Descarga gratuita", "Funciones Pro opcionales")],
            "why_kicker": "Una forma mejor de aprender", "why_title": "Practica con un propósito.",
            "why_text": "Cada modo tiene un objetivo claro: ganar fluidez, entender un método o desarrollar el razonamiento.",
            "benefits": [("Juega para ganar fluidez", "Desafío de Velocidad, Modo Supervivencia, Desafío de velocidad por parejas y los retos convierten la repetición en una experiencia dinámica."), ("Detente para comprender", "Las pistas visuales y los tutoriales muestran los pasos de la aritmética y el álgebra, no solo la respuesta."), ("Vuelve con un objetivo", "Marcas personales, dominio de tablas e historial de La Academia muestran dónde seguir practicando.")],
            "screens_kicker": "Mira la app real", "screens_title": "Cuatro formas de ganar confianza.",
            "screens_text": "Desde un minuto de cálculo mental hasta una ecuación guiada, siempre hay un punto de partida claro y respuesta inmediata.",
            "screen_captions": [("Corre contra el reloj", "Mejora la fluidez de cálculo"), ("Aprende a tu ritmo", "Consulta un método visual"), ("Domina las tablas", "Practica del 1 al 12"), ("Resuelve paso a paso", "Comprende el álgebra inicial")],
            "view_screens": "Ver todas las pantallas", "compare": "Comparar las funciones",
            "audience_kicker": "Una app, distintos objetivos", "audience_title": "Las mentes inquietas nunca dejan de crecer.",
            "audience_text": "El modo de aprendizaje tranquilo y los retos dinámicos sirven para descubrir un concepto, reforzar la confianza escolar o ejercitar la mente cada día.",
            "audiences": [("Niños y familias", "Construye bases sin miedo.", "Elige operaciones y dificultad adaptadas a la edad y abre una explicación visual cuando la necesites.", "Leer la guía para familias"), ("Jóvenes y adultos", "Mantén ágiles las matemáticas cotidianas.", "Repasa aritmética, porcentajes, fracciones, raíces, tablas o álgebra en sesiones breves.", "Buscar un modo de práctica")],
            "cta_kicker": "Cuando quieras", "cta_title": "Aprovecha los próximos cinco minutos.",
            "cta_text": "Descarga Pitagorin gratis para iPhone y iPad. Las funciones Pro opcionales están disponibles mediante compras dentro de la app.",
        },
        "features": {
            "title": "Funciones de Pitagorin | Aritmética, tablas y álgebra", "description": "Descubre los juegos de aritmética, el modo Aprendizaje, las tablas, la Academia, los retos y el álgebra guiada de Pitagorin.",
            "hero_kicker": "Dentro de Pitagorin", "hero_title": "Seis caminos. Un objetivo claro.",
            "hero_text": "Elige un juego rápido, una explicación tranquila, práctica de tablas, un examen propio, un reto de razonamiento o álgebra guiada.",
            "compare": "Comparar los modos", "real": "Ver la app real",
            "modes_kicker": "Elige tu camino", "modes_title": "Un modo para cada tipo de práctica.", "modes_text": "Cada función responde a una necesidad distinta y permite elegir intensidad, tema y nivel de ayuda.",
            "modes": [("Fluidez", "Juegos de aritmética", "Practica sumas, restas, multiplicaciones, divisiones, fracciones, decimales, porcentajes, potencias, raíces y más en tres niveles."), ("Comprensión", "Modo Aprendizaje", "Trabaja sin cronómetro, escribe la respuesta y abre pistas visuales específicas para cada operación."), ("Memoria", "Tablas de Multiplicar", "Aprende las tablas del 1 al 12. Pitagorin Pro añade Repaso inteligente y Sprint de fluidez."), ("Práctica independiente", "La Academia", "Crea un examen con operaciones y dificultad, guarda el resultado y revisa después los tutoriales."), ("Razonamiento", "Juegos matemáticos", "Alcanza un número objetivo o equilibra ambos lados de una ecuación con pistas y deshacer."), ("Siguiente paso", "Álgebra guiada", "Avanza por fundamentos, ecuaciones, proporciones, relaciones lineales, sistemas, exponentes y funciones.")],
            "loop_kicker": "El ciclo de aprendizaje", "loop_title": "Prueba. Comprende. Vuelve a probar.", "loop_text": "La respuesta rápida mantiene el ritmo y los tutoriales dejan espacio para comprender de verdad.",
            "loop": ["Elige una operación, tabla, tema o reto", "Ajusta la dificultad", "Usa ayuda visual cuando lo necesites", "Vuelve al progreso y a tus mejores marcas"],
            "calm": "Aprende con calma", "calm_sub": "Práctica sin tiempo y con ayuda", "reason": "Razona con claridad", "reason_sub": "Guía paso a paso",
            "path_kicker": "Cómo funciona una sesión", "path_title": "Una entrada sencilla a las matemáticas.", "path_text": "Pitagorin mantiene clara la siguiente acción para un niño independiente o un adulto que retoma las matemáticas.",
            "path": [("Elige", "Escoge un tema o juego para el objetivo de hoy."), ("Prueba", "Trabaja con un nivel y ritmo cómodos."), ("Comprende", "Abre una pista o tutorial cuando lo necesites."), ("Vuelve", "Gana dominio o supera tu marca.")],
            "cta_kicker": "Empieza a practicar", "cta_title": "Encuentra el modo que encaja contigo.", "cta_text": "Pitagorin se descarga gratis en iPhone y iPad, con funciones Pro opcionales dentro de la app.",
        },
        "screenshots": {
            "title": "Imágenes de Pitagorin | Juegos y aprendizaje guiado", "description": "Mira pantallas reales de Pitagorin con cálculo rápido, aprendizaje sin tiempo, tablas y álgebra paso a paso.",
            "hero_kicker": "La experiencia real", "hero_title": "Claro para aprender. Atractivo para volver.", "hero_text": "Estas son pantallas reales de Pitagorin. Cada una combina una tarea matemática concreta con señales visuales y una siguiente acción clara.",
            "gallery_kicker": "Cuatro momentos de aprendizaje", "gallery_title": "De recordar rápido a razonar con guía.", "gallery_text": "La interfaz se adapta al objetivo: dinámica para los retos, tranquila para aprender y explícita para el álgebra.",
            "captions": [("Desafío de Velocidad", "Cálculo mental breve y dinámico"), ("Modo Aprendizaje", "Práctica sin tiempo con ayuda visual"), ("Tablas de Multiplicar", "Recuerdo enfocado de las tablas 1–12"), ("Álgebra guiada", "Razona las ecuaciones paso a paso")],
            "focus_kicker": "Diseñada para concentrarse", "focus_title": "La decoración también tiene una función.", "focus_text": "El color invita a entrar, mientras la zona de trabajo sigue siendo amplia y legible. Las preguntas, respuestas y controles mantienen la prioridad.",
            "focus": [("Preguntas legibles", "Expresiones grandes y buen espaciado hacen fácil localizar la tarea."), ("Opciones claras", "Cada pantalla limita las acciones para que el siguiente paso sea evidente."), ("Ayuda cuando hace falta", "El apoyo aparece cuando es útil, sin interrumpir cada intento."), ("Progreso visible", "Puntuaciones, tiempo, dominio e historial dan una dirección concreta.")],
            "cta_kicker": "Da el siguiente paso", "cta_title": "Prueba la experiencia real.", "cta_text": "Descarga Pitagorin gratis en iPhone o iPad, o descubre antes todos los modos.", "explore": "Explorar funciones",
        },
        "parents": {
            "title": "Pitagorin para familias | Matemáticas para 5–13 años", "description": "Descubre cómo Pitagorin ayuda a niños de 5 a 13 años a practicar con dificultad adaptada, tutoriales visuales, tablas, progreso y álgebra.",
            "hero_kicker": "Para niños y los adultos que los acompañan", "hero_title": "La confianza empieza cuando el método tiene sentido.", "hero_text": "Pitagorin ayuda a niños de 5 a 13 años a practicar de forma independiente, elegir un reto adecuado y consultar una explicación visual clara.",
            "download": "Descargar Pitagorin gratis", "expect_link": "Qué pueden esperar las familias",
            "expect_kicker": "Un equilibrio cuidado", "expect_title": "Independencia con ayuda cerca.", "expect_text": "Ofrece elecciones con sentido sin dejar al niño adivinando qué hacer después. El objetivo es practicar con propósito, no acumular tiempo de pantalla.",
            "expect": [("Empieza en el nivel adecuado", "Las operaciones adaptadas a la edad y tres dificultades permiten comenzar con un reto manejable."), ("Mira cómo funciona", "Los tutoriales explican llevadas, préstamos, fracciones, raíces, prioridad de operaciones y otras bases."), ("Observa el progreso real", "Marcas, dominio de tablas, historial de Academia y puntuaciones hacen visible la mejora.")],
            "practice_kicker": "Qué pueden practicar", "practice_title": "De los primeros cálculos al álgebra.", "practice_text": "Pueden seguir el tema de clase o dejarse llevar por la curiosidad.",
            "practice": ["Suma, resta, multiplicación y división", "Fracciones, decimales, porcentajes, potencias y raíces", "Tablas del 1 al 12", "Ecuaciones, proporciones, funciones y relaciones lineales", "Retos numéricos y juegos de equilibrio de ecuaciones"],
            "care_kicker": "Conviene saberlo", "care_title": "Diseñada con cuidado.", "care_text": "Pitagorin se descarga gratis con funciones Pro opcionales. No necesita cuenta y el progreso principal permanece en el dispositivo.",
            "care": [("Sin cuenta", "No se pide al niño nombre, correo ni perfil para empezar."), ("Los datos de aprendizaje son locales", "Progreso, puntuaciones, dominio y fotos opcionales se guardan en el dispositivo."), ("Accesibilidad", "Admite texto grande, modo oscuro, movimiento reducido y descripciones compatibles con VoiceOver."), ("Privacidad clara", "Consulta la política breve para conocer los detalles sobre anuncios, analítica, compras y fotos.")],
            "cta_kicker": "Para todas las mentes", "cta_title": "Los niños guían el diseño. Todos pueden practicar.", "cta_text": "Jóvenes y adultos también pueden repasar matemáticas básicas, mejorar el cálculo mental o mantener la mente activa.",
        },
        "faq_page": {
            "title": "Preguntas sobre Pitagorin | Edad, temas, dispositivos y privacidad", "description": "Respuestas sobre edades, contenidos, tutoriales, iPhone y iPad, práctica adulta, privacidad, anuncios y Pitagorin Pro.",
            "hero_kicker": "Respuestas claras", "hero_title": "¿Qué quieres saber?", "hero_text": "Una guía breve sobre las personas que usan Pitagorin, sus temas, la ayuda, los dispositivos, la privacidad, los anuncios y Pro.",
            "questions": [("¿Para qué edad es Pitagorin?", "Está diseñada principalmente para niños de 5 a 13 años. La dificultad y los temas también sirven a jóvenes y adultos que quieren repasar."), ("¿Qué matemáticas se pueden practicar?", "Suma, resta, multiplicación, división, fracciones, decimales, porcentajes, potencias, raíces, tablas 1–12, ecuaciones, proporciones, funciones y relaciones lineales."), ("¿Pitagorin explica cómo resolver un problema?", "Sí. Aprendizaje incluye pistas visuales y métodos escritos; Álgebra ofrece resolución guiada paso a paso."), ("¿Qué dispositivos admite?", "Está disponible para iPhone y iPad con iOS 18 o iPadOS 18, o posteriores."), ("¿Pueden usarla jóvenes y adultos?", "Sí. Las sesiones breves de aritmética, tablas, cálculo mental y álgebra ayudan a refrescar conocimientos y mantener la mente activa."), ("¿Hace falta una cuenta?", "No. No se requiere cuenta, nombre ni correo. El progreso se guarda localmente."), ("¿Pitagorin es gratis?", "La descarga es gratuita. Pitagorin Pro ofrece funciones opcionales mediante compras dentro de la app."), ("¿Muestra publicidad?", "La versión gratuita puede mostrar anuncios intersticiales ocasionales. Pitagorin Pro no muestra anuncios.")],
            "cta_kicker": "¿Sigues explorando?", "cta_title": "Mira cómo se aprende.", "cta_text": "Compara los modos, recorre pantallas reales o lee la guía para familias.",
        },
        "privacy_page": {
            "title": "Política de privacidad de Pitagorin | Prácticas de datos claras", "description": "Cómo gestiona Pitagorin los datos locales, fotos opcionales, anuncios, analítica, compras y privacidad infantil.",
            "hero_kicker": "Privacidad sin complicaciones", "hero_title": "Política de privacidad de Pitagorin", "hero_text": "En breve: no hace falta una cuenta, los datos de aprendizaje permanecen en el dispositivo y no se pide nombre ni correo.",
            "updated": "Última actualización:", "date": "3 de septiembre de 2026 · Desarrollador: Lorenzo Villarroel Perez", "on_page": "En esta página",
            "nav": [("on-device", "Datos en el dispositivo"), ("services", "Anuncios y analítica"), ("photos", "Fotos y compras"), ("children", "Niños y familias"), ("choices", "Tus opciones")],
            "summary": [("Sin cuenta", "No hace falta nombre ni correo"), ("Progreso local", "Los datos permanecen en el dispositivo"), ("Pro sin anuncios", "Los usuarios Pro no ven publicidad")],
            "sections": [("on-device", "Qué permanece en tu dispositivo", ["Pitagorin guarda localmente ajustes, progreso, puntuaciones, marcas, dominio de tablas, historial de Academia y fotos opcionales del trabajo escrito. No sube estos datos a servidores propios; pueden aplicarse las copias de seguridad controladas por Apple.", "Puedes eliminar los datos locales borrando la app. No hace falta una cuenta."]), ("services", "Publicidad y analítica del producto", ["Esta web estática no tiene inicio de sesión, formulario de contacto, publicidad, analítica ni cookies de Pitagorin.", "La app gratuita puede mostrar anuncios intersticiales ocasionales mediante Google Mobile Ads (AdMob). Pro no muestra anuncios. La publicidad se configura para público infantil, con contenido general y sin personalización. Rechazar el permiso de seguimiento no impide aprender.", "Firebase Analytics mide el uso agregado de áreas y modos. Excluye nombres, cuentas, respuestas, ecuaciones, puntuaciones, progreso, identificadores de compra o publicidad, ubicación precisa y fotos."]), ("photos", "Fotos y compras", ["Solo se solicita cámara o fototeca si decides adjuntar trabajo escrito a un examen de Academia. La foto permanece en el historial local.", "Apple procesa los pagos de Pro mediante App Store y StoreKit. Pitagorin recibe el estado necesario para desbloquear Pro, no los datos de tu tarjeta o banco."]), ("children", "Niños, familias y adultos", ["Pitagorin está pensada para niños y familias y también es adecuada para jóvenes y adultos. No pide a los niños crear una cuenta ni facilitar datos de contacto. Padres y tutores deberían revisar con ellos los ajustes del dispositivo, App Store, publicidad y copias de seguridad."]), ("choices", "Tus opciones y preguntas", ["Puedes rechazar el seguimiento, no adjuntar fotos y borrar la app para eliminar los datos locales. Para preguntas de privacidad, utiliza el contacto del desarrollador en la ficha de Pitagorin del App Store.", "Esta página se actualizará si cambian las prácticas de datos de Pitagorin."])],
        },
    },
    "de": {
        "common": {"skip":"Zum Inhalt springen","primary":"Hauptnavigation","home":"Pitagorin Startseite","features":"Funktionen","screenshots":"App-Ansichten","families":"Für Familien","faq":"FAQ","privacy":"Datenschutz","get":"App laden","menu":"Menü","terms":"Nutzungsbedingungen","footer_nav":"Navigation im Seitenfuß","footer":"Spielerisches, geführtes Mathetraining für Kinder, Familien und alle, die weiterlernen möchten.","available":"Pitagorin. Im App Store erhältlich.","store":"Im App Store öffnen","all_features":"Alle Funktionen entdecken"},
        "index": {
            "title":"Pitagorin Mathe-App | Spiele, Einmaleins und Algebra","description":"Mathe sicherer meistern mit Rechenspielen, Einmaleins, visuellen Erklärungen und geführter Algebra auf iPhone und iPad. Für Kinder von 5–13 und Erwachsene.","og":"Pitagorin – Mathetraining, das sich wie Spielen anfühlt",
            "hero_kicker":"Einladendes Mathetraining","hero_title":"Verstehen. Üben. Sicher können.","hero_text":"Pitagorin macht aus Rechnen, Einmaleins und erster Algebra kurze, konzentrierte Einheiten mit klaren Erklärungen. Für Kinder von 5 bis 13 Jahren entwickelt – und ebenso nützlich für Erwachsene, die Alltagsmathematik auffrischen möchten.","download":"Kostenlos im App Store laden","explore":"Lernmodi entdecken","device":"Für iPhone und iPad erhältlich",
            "proof":[["5–13 Jahre","Altersgerechte Grundlagen"],["Erwachsene willkommen","Kurze Auffrischungen"],["iPhone + iPad","iOS 18 oder neuer"],["Kostenlos laden","Optionale Pro-Funktionen"]],
            "why_kicker":"Ein besserer Lernkreislauf","why_title":"Üben mit einem Ziel.","why_text":"Jeder Modus verfolgt ein klares Ziel: flüssiger rechnen, einen Rechenweg verstehen oder logisch denken.",
            "benefits":[["Spielend flüssiger rechnen","Blitz-Challenge, Überlebensmodus, Geschwindigkeitsduell und Denkaufgaben machen Wiederholung lebendig."],["In Ruhe verstehen","Visuelle Hinweise und schriftliche Methoden zeigen jeden Schritt in Arithmetik und Algebra."],["Gezielt zurückkehren","Bestleistungen, Einmaleins-Fortschritt und Akademie-Verlauf zeigen, was als Nächstes geübt werden kann."]],
            "screens_kicker":"Die echte App ansehen","screens_title":"Vier Wege zu mehr Sicherheit.","screens_text":"Vom einminütigen Kopfrechensprint bis zur geführten Gleichung gibt es einen klaren Startpunkt und direktes Feedback.","screen_captions":[["Rechne gegen die Zeit","Stärke die Rechenflüssigkeit"],["Lerne in deinem Tempo","Nutze einen visuellen Rechenweg"],["Meistere dein Einmaleins","Übe die Reihen 1 bis 12"],["Löse Schritt für Schritt","Verstehe erste Algebra"]],"view_screens":"Alle App-Ansichten","compare":"Alle Funktionen vergleichen",
            "audience_kicker":"Eine App, verschiedene Ziele","audience_title":"Lernende Köpfe wachsen weiter.","audience_text":"Ruhiges Lernen und lebendige Herausforderungen passen zum ersten Kontakt mit einem Thema, zur schulischen Stärkung oder zum täglichen Gehirntraining.","audiences":[["Kinder & Familien","Grundlagen ohne Angst aufbauen.","Wähle altersgerechte Rechenarten und Schwierigkeit und öffne bei Bedarf eine visuelle Erklärung.","Familienratgeber lesen"],["Jugendliche & Erwachsene","Alltagsmathematik fit halten.","Frische Rechnen, Prozente, Brüche, Wurzeln, Einmaleins oder Algebra in kurzen Einheiten auf.","Übungsmodus finden"]],
            "cta_kicker":"Wann immer du bereit bist","cta_title":"Nutze die nächsten fünf Minuten.","cta_text":"Lade Pitagorin kostenlos für iPhone und iPad. Optionale Pro-Funktionen sind als In-App-Käufe verfügbar."
        },
        "features": {
            "title":"Pitagorin Funktionen | Rechenspiele, Einmaleins und Algebra","description":"Entdecke Rechenspiele, Lernmodus, Einmaleins, Akademie, Denkaufgaben und geführte Algebra in Pitagorin.","hero_kicker":"In Pitagorin","hero_title":"Sechs Wege. Ein klares Ziel.","hero_text":"Wähle ein schnelles Rechenspiel, eine ruhige Erklärung, Einmaleins-Training, eine eigene Prüfung, eine Denkaufgabe oder geführte Algebra.","compare":"Modi vergleichen","real":"Echte App ansehen",
            "modes_kicker":"Wähle deinen Weg","modes_title":"Ein Modus für jede Art des Übens.","modes_text":"Jede Funktion erfüllt ein anderes Lernbedürfnis. Intensität, Thema und Unterstützung bleiben wählbar.",
            "modes":[["Rechenflüssigkeit","Rechenspiele","Übe Addition, Subtraktion, Multiplikation, Division, Brüche, Dezimalzahlen, Prozente, Potenzen, Wurzeln und mehr in drei Stufen."],["Verständnis","Lernmodus","Arbeite ohne Zeitdruck, gib die Antwort ein und öffne passende visuelle Hilfen."],["Abruf","Einmaleins","Lerne die Reihen 1 bis 12. Pitagorin Pro ergänzt Intelligente Wiederholung und Flüssigkeits-Sprint."],["Selbstständiges Üben","Die Akademie","Stelle eine Prüfung aus Rechenarten und Schwierigkeit zusammen, speichere das Ergebnis und sieh Erklärungen erneut an."],["Logisches Denken","Mathe-Spiele","Erreiche eine Zielzahl oder gleiche beide Seiten einer Gleichung mit Hinweisen und Rückgängig aus."],["Nächster Schritt","Geführte Algebra","Folge Grundlagen, Gleichungen, proportionalem Denken, linearen Zusammenhängen, Systemen, Exponenten und Funktionen."]],
            "loop_kicker":"Der Lernkreislauf","loop_title":"Probieren. Verstehen. Noch einmal.","loop_text":"Schnelles Feedback hält den Schwung; Erklärungen schaffen echtes Verständnis.","loop":["Wähle Rechenart, Reihe, Thema oder Aufgabe","Passe die Schwierigkeit an","Nutze visuelle Hilfe, wenn du sie brauchst","Kehre zu Fortschritt und Bestleistungen zurück"],"calm":"Lerne in Ruhe","calm_sub":"Ohne Zeitdruck und mit Hilfe","reason":"Denke klar","reason_sub":"Schrittweise Anleitung",
            "path_kicker":"So läuft eine Einheit","path_title":"Ein einfacher Weg in die Mathematik.","path_text":"Der nächste Schritt bleibt für selbstständige Kinder und zurückkehrende Erwachsene verständlich.","path":[["Wählen","Thema oder Spiel passend zum heutigen Ziel auswählen."],["Probieren","Auf angenehmer Stufe und im eigenen Tempo arbeiten."],["Verstehen","Bei Bedarf Hinweis oder Erklärung öffnen."],["Zurückkehren","Sicherheit aufbauen oder Bestleistung verbessern."]],"cta_kicker":"Jetzt üben","cta_title":"Finde den Modus, der passt.","cta_text":"Pitagorin ist für iPhone und iPad kostenlos, mit optionalen Pro-Funktionen in der App."
        },
        "screenshots": {"title":"Pitagorin App-Ansichten | Mathe-Spiele und geführtes Lernen","description":"Sieh echte Pitagorin-Ansichten für schnelles Rechnen, ruhiges Lernen, Einmaleins und Algebra Schritt für Schritt.","hero_kicker":"Das echte Erlebnis","hero_title":"Klar genug zum Lernen. Fröhlich genug zum Wiederkommen.","hero_text":"Das sind echte Pitagorin-Ansichten. Jede verbindet eine klare Matheaufgabe mit einladenden visuellen Signalen und einem verständlichen nächsten Schritt.","gallery_kicker":"Vier Lernmomente","gallery_title":"Vom schnellen Abruf zum geführten Denken.","gallery_text":"Die Oberfläche passt sich dem Ziel an: lebendig für Herausforderungen, ruhig zum Lernen und deutlich für Algebra.","captions":[["Blitz-Challenge","Kurzes, lebendiges Kopfrechnen"],["Lernmodus","Üben ohne Zeitdruck mit visueller Hilfe"],["Einmaleins","Gezielter Abruf der Reihen 1–12"],["Geführte Algebra","Gleichungen Schritt für Schritt verstehen"]],"focus_kicker":"Für Konzentration gestaltet","focus_title":"Auch die Gestaltung hat eine Aufgabe.","focus_text":"Farbe lädt zum Mitmachen ein, während der Arbeitsbereich großzügig und lesbar bleibt.","focus":[["Lesbare Aufgaben","Große Ausdrücke und viel Abstand machen die Aufgabe leicht auffindbar."],["Klare Auswahl","Wenige konkurrierende Aktionen zeigen, was als Nächstes zu tun ist."],["Hilfe bei Bedarf","Unterstützung erscheint, wenn sie nützt, statt jeden Versuch zu unterbrechen."],["Sichtbarer Fortschritt","Punkte, Zeit, Lernstand und Verlauf geben dem Üben Richtung."]],"cta_kicker":"Der nächste Schritt","cta_title":"Probiere es selbst aus.","cta_text":"Lade Pitagorin kostenlos auf iPhone oder iPad oder entdecke zuerst alle Modi.","explore":"Funktionen entdecken"},
        "parents": {"title":"Pitagorin für Familien | Mathe-App für 5–13 Jahre","description":"So unterstützt Pitagorin Kinder von 5–13 beim selbstständigen Üben mit passender Schwierigkeit, visuellen Erklärungen, Einmaleins und Algebra.","hero_kicker":"Für Kinder und Erwachsene an ihrer Seite","hero_title":"Sicherheit wächst, wenn der Rechenweg Sinn ergibt.","hero_text":"Pitagorin hilft Kindern von 5 bis 13, selbstständig zu üben, eine passende Herausforderung zu wählen und bei Bedarf eine klare visuelle Erklärung zu öffnen.","download":"Pitagorin kostenlos laden","expect_link":"Was Familien erwarten können","expect_kicker":"Sorgfältig ausgewogen","expect_title":"Selbstständigkeit mit Hilfe in Reichweite.","expect_text":"Kinder treffen sinnvolle Entscheidungen, ohne beim nächsten Schritt allein zu sein. Ziel ist bewusstes Üben, nicht endlose Bildschirmzeit.","expect":[["Auf der passenden Stufe starten","Altersgerechte Rechenarten und drei Schwierigkeitsstufen bieten einen machbaren Einstieg."],["Den Rechenweg sehen","Erklärungen behandeln Übertrag, Entbündeln, Brüche, Wurzeln, Rechenregeln und weitere Grundlagen."],["Echten Fortschritt erkennen","Bestleistungen, Einmaleins-Stand, Akademie-Verlauf und Punkte machen Verbesserung sichtbar."]],"practice_kicker":"Was Kinder üben können","practice_title":"Von ersten Aufgaben bis zu Algebra.","practice_text":"Kinder können beim aktuellen Schulthema bleiben oder ihrer Neugier folgen.","practice":["Addition, Subtraktion, Multiplikation und Division","Brüche, Dezimalzahlen, Prozente, Potenzen und Wurzeln","Einmaleins von 1 bis 12","Gleichungen, Verhältnisse, Funktionen und lineare Zusammenhänge","Zahlenrätsel und Gleichgewichtsaufgaben"],"care_kicker":"Gut zu wissen","care_title":"Mit Sorgfalt entwickelt.","care_text":"Pitagorin ist kostenlos mit optionalen Pro-Funktionen. Kein Konto ist nötig; der Lernfortschritt bleibt auf dem Gerät.","care":[["Kein Konto nötig","Kinder müssen weder Namen noch E-Mail oder Profil angeben."],["Lerndaten bleiben lokal","Fortschritt, Punkte, Lernstand und optionale Fotos liegen auf dem Gerät."],["Barrierefreiheit bedacht","Größerer Text, Dark Mode, reduzierte Bewegung und VoiceOver-Beschreibungen werden unterstützt."],["Klare Datenschutzinfos","Die kurze Richtlinie erklärt Werbung, Analyse, Käufe und Fotos."]],"cta_kicker":"Für jeden lernenden Kopf","cta_title":"Kinder bestimmen das Design. Alle können üben.","cta_text":"Auch Jugendliche und Erwachsene können Grundrechenarten auffrischen, Kopfrechnen stärken oder geistig aktiv bleiben."},
        "faq_page": {"title":"Pitagorin FAQ | Alter, Themen, Geräte und Datenschutz","description":"Antworten zu Alter, Mathethemen, Erklärungen, iPhone und iPad, Üben für Erwachsene, Datenschutz, Werbung und Pro.","hero_kicker":"Klare Antworten","hero_title":"Was möchtest du wissen?","hero_text":"Ein kurzer Überblick über Lernende, Themen, Unterstützung, Geräte, Datenschutz, Werbung und Pro.","questions":[["Für welches Alter ist Pitagorin gedacht?","Vor allem für Kinder von 5 bis 13 Jahren. Schwierigkeit und breitere Themen eignen sich auch für Jugendliche und Erwachsene."],["Welche Mathematik kann man üben?","Addition, Subtraktion, Multiplikation, Division, Brüche, Dezimalzahlen, Prozente, Potenzen, Wurzeln, Einmaleins, Gleichungen, Verhältnisse und Funktionen."],["Erklärt Pitagorin Lösungswege?","Ja. Der Lernmodus bietet visuelle Hinweise und schriftliche Methoden; Algebra erklärt das Lösen Schritt für Schritt."],["Welche Geräte werden unterstützt?","iPhone und iPad mit iOS 18 beziehungsweise iPadOS 18 oder neuer."],["Können Jugendliche und Erwachsene Pitagorin nutzen?","Ja. Kurze Einheiten frischen Fähigkeiten auf und halten den Kopf aktiv."],["Ist ein Konto nötig?","Nein. Name und E-Mail sind nicht erforderlich; der Fortschritt bleibt auf dem Gerät."],["Ist Pitagorin kostenlos?","Die App ist kostenlos. Optionale Pro-Funktionen sind als In-App-Käufe erhältlich."],["Zeigt Pitagorin Werbung?","Die kostenlose Version kann gelegentlich Vollbildwerbung zeigen. Pro ist werbefrei."]],"cta_kicker":"Noch neugierig?","cta_title":"Sieh dir das Lernen an.","cta_text":"Vergleiche Modi, entdecke echte App-Ansichten oder lies den Familienratgeber."},
        "privacy_page": {"title":"Pitagorin Datenschutz | Klare Datenpraxis","description":"Wie Pitagorin lokale Lerndaten, optionale Fotos, Werbung, Analyse, Käufe und den Datenschutz von Kindern behandelt.","hero_kicker":"Datenschutz ohne Rätsel","hero_title":"Pitagorin Datenschutzerklärung","hero_text":"Kurz gesagt: Kein Konto ist nötig, Lerndaten bleiben auf dem Gerät und Pitagorin fragt nicht nach Name oder E-Mail.","updated":"Zuletzt aktualisiert:","date":"3. September 2026 · Entwickler: Lorenzo Villarroel Perez","on_page":"Auf dieser Seite","nav":[["on-device","Daten auf dem Gerät"],["services","Werbung und Analyse"],["photos","Fotos und Käufe"],["children","Kinder und Familien"],["choices","Deine Auswahl"]],"summary":[["Kein Konto","Name und E-Mail nicht nötig"],["Lokaler Fortschritt","Lerndaten bleiben auf dem Gerät"],["Pro ohne Werbung","Keine Werbung für Pro"]],"sections":[["on-device","Was auf deinem Gerät bleibt",["Pitagorin speichert Einstellungen, Fortschritt, Punkte, Bestleistungen, Einmaleins-Stand, Akademie-Verlauf und optionale Fotos schriftlicher Arbeit lokal. Diese Lerndaten werden nicht auf eigene Server hochgeladen; von Apple verwaltete Backups können gelten.","Lokale Daten lassen sich durch Löschen der App entfernen. Ein Konto ist nicht erforderlich."]],["services","Werbung und Produktanalyse",["Diese statische Website hat keine Anmeldung, kein Kontaktformular, keine Werbung, keine Analyse und keine Pitagorin-Cookies.","Die kostenlose App kann gelegentlich Vollbildwerbung über Google Mobile Ads zeigen. Pro ist werbefrei. Werbung ist kindgerecht, allgemein eingestuft und nicht personalisiert. Eine abgelehnte Tracking-Erlaubnis verhindert das Lernen nicht.","Firebase Analytics misst die zusammengefasste Nutzung von Bereichen und Modi. Namen, Konten, Antworten, Gleichungen, Punkte, Fortschritt, Kauf- und Werbe-IDs, genauer Standort und Fotos sind ausgeschlossen."]],["photos","Fotos und Käufe",["Kamera oder Fotomediathek werden nur angefragt, wenn du schriftliche Arbeit an eine Akademie-Prüfung anhängst. Das Foto bleibt im lokalen Verlauf.","Apple verarbeitet Pro-Zahlungen über App Store und StoreKit. Pitagorin erhält den Freischaltstatus, nicht Karten- oder Bankdaten."]],["children","Kinder, Familien und Erwachsene",["Pitagorin wurde für Kinder und Familien entwickelt und eignet sich auch für Jugendliche und Erwachsene. Kinder müssen kein Konto erstellen oder Kontaktdaten angeben. Eltern sollten Geräte-, App-Store-, Werbe- und Backup-Einstellungen gemeinsam prüfen."]],["choices","Deine Auswahl und Fragen",["Du kannst Tracking ablehnen, keine Fotos anhängen und die App löschen, um lokale Daten zu entfernen. Datenschutzfragen können über den Entwicklerkontakt im App Store gestellt werden.","Diese Seite wird aktualisiert, wenn sich die Datenpraxis ändert."]]]}
    },
    "fr": {
        "common":{"skip":"Aller au contenu","primary":"Navigation principale","home":"Accueil Pitagorin","features":"Fonctionnalités","screenshots":"L’app","families":"Pour les familles","faq":"Questions","privacy":"Confidentialité","get":"Télécharger","menu":"Menu","terms":"Conditions","footer_nav":"Navigation de pied de page","footer":"Des maths ludiques et guidées pour les enfants, les familles et tous ceux qui souhaitent continuer à apprendre.","available":"Pitagorin. Disponible sur l’App Store.","store":"Ouvrir l’App Store","all_features":"Découvrir toutes les fonctionnalités"},
        "index":{"title":"Pitagorin : application de maths | Jeux, tables et algèbre","description":"Développe ta confiance avec des jeux de calcul, les tables, des explications visuelles et l’algèbre guidée sur iPhone et iPad. Pour les 5–13 ans et les adultes.","og":"Pitagorin : pratiquer les maths en jouant","hero_kicker":"Des maths qui donnent envie","hero_title":"Comprends. Entraîne-toi. Progresse.","hero_text":"Pitagorin transforme le calcul, les tables et les débuts en algèbre en séances courtes avec des explications claires. Conçue pour les enfants de 5 à 13 ans, elle aide aussi les adultes à réviser les maths du quotidien.","download":"Télécharger gratuitement","explore":"Découvrir les modes d’apprentissage","device":"Disponible sur iPhone et iPad","proof":[["5–13 ans","Des bases adaptées à l’âge"],["Adultes bienvenus","Des révisions rapides"],["iPhone + iPad","iOS 18 ou version ultérieure"],["Téléchargement gratuit","Fonctions Pro facultatives"]],"why_kicker":"Un meilleur cycle d’apprentissage","why_title":"S’entraîner avec une raison.","why_text":"Chaque mode a un objectif clair : gagner en fluidité, comprendre une méthode ou développer le raisonnement.","benefits":[["Joue pour gagner en fluidité","Défi Vitesse, Mode Survie, Défi de vitesse en duel et les défis rendent la répétition dynamique."],["Fais une pause pour comprendre","Les aides visuelles et les méthodes posées montrent chaque étape du calcul et de l’algèbre."],["Reviens avec un objectif","Records, maîtrise des tables et historique de l’Académie montrent quoi travailler ensuite."]],"screens_kicker":"Découvre la vraie app","screens_title":"Quatre façons de prendre confiance.","screens_text":"Du sprint de calcul mental d’une minute à l’équation guidée, le point de départ reste clair et le retour immédiat.","screen_captions":[["Défie le chrono","Développe la fluidité de calcul"],["Apprends à ton rythme","Demande une méthode visuelle"],["Maîtrise tes tables","Entraîne-toi de 1 à 12"],["Résous pas à pas","Comprends les bases de l’algèbre"]],"view_screens":"Voir toutes les interfaces","compare":"Comparer les fonctionnalités","audience_kicker":"Une app, plusieurs objectifs","audience_title":"L’envie d’apprendre n’a pas d’âge.","audience_text":"Le mode calme et les défis dynamiques conviennent à la découverte d’une notion, au renforcement scolaire ou à l’exercice quotidien de l’esprit.","audiences":[["Enfants et familles","Construire des bases sans crainte.","Choisis des opérations et une difficulté adaptées à l’âge, puis ouvre une explication visuelle si nécessaire.","Lire le guide des familles"],["Ados et adultes","Entretenir les maths du quotidien.","Révise calcul, pourcentages, fractions, racines, tables ou algèbre en séances courtes.","Trouver un mode"]],"cta_kicker":"Quand tu veux","cta_title":"Mets à profit les cinq prochaines minutes.","cta_text":"Télécharge Pitagorin gratuitement sur iPhone et iPad. Des fonctions Pro facultatives sont proposées par achat intégré."},
        "features":{"title":"Fonctionnalités Pitagorin | Calcul, tables et algèbre","description":"Découvre les jeux de calcul, le mode Apprentissage, les tables, l’Académie, les défis et l’algèbre guidée de Pitagorin.","hero_kicker":"Dans Pitagorin","hero_title":"Six parcours. Un objectif clair.","hero_text":"Choisis un jeu rapide, une explication calme, les tables, ton propre examen, un défi de raisonnement ou l’algèbre guidée.","compare":"Comparer les modes","real":"Voir la vraie app","modes_kicker":"Choisis ton parcours","modes_title":"Un mode pour chaque façon de s’entraîner.","modes_text":"Chaque fonction répond à un besoin précis avec un choix d’intensité, de sujet et d’accompagnement.","modes":[["Fluidité","Jeux de calcul","Entraîne-toi à l’addition, la soustraction, la multiplication, la division, les fractions, les décimaux, les pourcentages, les puissances, les racines et plus encore."],["Compréhension","Mode Apprentissage","Travaille sans chronomètre, saisis ta réponse et ouvre des aides visuelles propres à chaque opération."],["Mémorisation","Tables de multiplication","Apprends les tables de 1 à 12. Pitagorin Pro ajoute Révision intelligente et Sprint de fluidité."],["Pratique autonome","L’Académie","Crée un examen avec les opérations et la difficulté de ton choix, enregistre le résultat et revois les explications."],["Raisonnement","Jeux mathématiques","Atteins un nombre cible ou équilibre les deux côtés d’une équation avec des indices et l’annulation."],["Étape suivante","Algèbre guidée","Progresse à travers les bases, équations, proportions, relations linéaires, systèmes, exposants et fonctions."]],"loop_kicker":"Le cycle d’apprentissage","loop_title":"Essaie. Comprends. Recommence.","loop_text":"Le retour rapide entretient l’élan et les explications permettent de vraiment comprendre.","loop":["Choisis une opération, une table, un thème ou un défi","Adapte la difficulté","Utilise une aide visuelle si nécessaire","Reviens à tes progrès et records"],"calm":"Apprends calmement","calm_sub":"Sans chronomètre et avec de l’aide","reason":"Raisonne clairement","reason_sub":"Un accompagnement pas à pas","path_kicker":"Déroulement d’une séance","path_title":"Un chemin simple vers les maths.","path_text":"L’action suivante reste claire pour un enfant autonome comme pour un adulte qui reprend les maths.","path":[["Choisis","Sélectionne un thème ou un jeu adapté à l’objectif du jour."],["Essaie","Travaille à un niveau et un rythme confortables."],["Comprends","Ouvre un indice ou une explication si besoin."],["Reviens","Développe ta maîtrise ou bats ton record."]],"cta_kicker":"Commence à pratiquer","cta_title":"Trouve le mode qui te correspond.","cta_text":"Pitagorin est gratuite sur iPhone et iPad, avec des fonctions Pro facultatives dans l’app."},
        "screenshots":{"title":"Images de Pitagorin | Jeux et apprentissage guidé","description":"Découvre de vraies interfaces Pitagorin pour le calcul rapide, l’apprentissage calme, les tables et l’algèbre pas à pas.","hero_kicker":"L’expérience réelle","hero_title":"Assez claire pour apprendre. Assez vive pour revenir.","hero_text":"Voici de vraies interfaces Pitagorin. Chacune associe une tâche précise à des repères visuels accueillants et une prochaine action claire.","gallery_kicker":"Quatre moments d’apprentissage","gallery_title":"Du rappel rapide au raisonnement guidé.","gallery_text":"L’interface s’adapte au but : dynamique pour un défi, calme pour apprendre et explicite pour l’algèbre.","captions":[["Défi Vitesse","Calcul mental court et dynamique"],["Mode Apprentissage","Pratique sans chronomètre avec aide visuelle"],["Tables de multiplication","Rappel ciblé des tables de 1 à 12"],["Algèbre guidée","Raisonne sur les équations pas à pas"]],"focus_kicker":"Conçue pour se concentrer","focus_title":"La décoration a aussi un rôle.","focus_text":"La couleur accueille l’élève, tandis que la zone de travail reste spacieuse et lisible.","focus":[["Questions lisibles","De grandes expressions et un espacement généreux rendent la tâche facile à repérer."],["Choix clairs","Chaque écran limite les actions concurrentes pour rendre la suite évidente."],["Aide à la demande","L’aide apparaît quand elle est utile sans interrompre chaque tentative."],["Progrès visibles","Scores, temps, maîtrise et historique donnent une direction concrète."]],"cta_kicker":"Passe à l’étape suivante","cta_title":"Essaie l’expérience réelle.","cta_text":"Télécharge Pitagorin gratuitement sur iPhone ou iPad, ou découvre d’abord tous les modes.","explore":"Découvrir les fonctionnalités"},
        "parents":{"title":"Pitagorin pour les familles | Maths pour les 5–13 ans","description":"Découvre comment Pitagorin aide les 5–13 ans à pratiquer avec une difficulté adaptée, des explications visuelles, les tables et l’algèbre.","hero_kicker":"Pour les enfants et les adultes à leurs côtés","hero_title":"La confiance commence quand la méthode devient claire.","hero_text":"Pitagorin aide les enfants de 5 à 13 ans à pratiquer seuls, choisir un défi adapté et ouvrir une explication visuelle lorsqu’ils en ont besoin.","download":"Télécharger Pitagorin gratuitement","expect_link":"Ce que les familles peuvent attendre","expect_kicker":"Un équilibre réfléchi","expect_title":"De l’autonomie, avec de l’aide à proximité.","expect_text":"Les enfants font des choix utiles sans devoir deviner la suite. Le but est une pratique intentionnelle, pas un temps d’écran sans fin.","expect":[["Commencer au bon niveau","Des opérations adaptées à l’âge et trois difficultés proposent un défi accessible."],["Voir comment faire","Les méthodes posées expliquent retenues, emprunts, fractions, racines, priorités et autres bases."],["Constater les progrès","Records, maîtrise des tables, historique de l’Académie et scores rendent les progrès visibles."]],"practice_kicker":"Ce que les enfants peuvent pratiquer","practice_title":"Des premiers calculs à l’algèbre.","practice_text":"Ils peuvent suivre le sujet vu en classe ou leur curiosité.","practice":["Addition, soustraction, multiplication et division","Fractions, décimaux, pourcentages, puissances et racines","Tables de 1 à 12","Équations, rapports, fonctions et relations linéaires","Défis numériques et jeux d’équilibre d’équations"],"care_kicker":"Bon à savoir","care_title":"Conçue avec soin.","care_text":"Pitagorin est gratuite avec des fonctions Pro facultatives. Aucun compte n’est requis et les progrès restent sur l’appareil.","care":[["Aucun compte","Ni nom, ni e-mail, ni profil ne sont demandés pour commencer."],["Données d’apprentissage locales","Progrès, scores, maîtrise et photos facultatives restent sur l’appareil."],["Accessibilité prise en compte","Texte agrandi, mode sombre, réduction des animations et descriptions VoiceOver sont pris en charge."],["Confidentialité claire","La politique concise explique publicité, analyse, achats et photos."]],"cta_kicker":"Pour tous les esprits","cta_title":"Les enfants guident la conception. Tout le monde peut pratiquer.","cta_text":"Ados et adultes peuvent aussi réviser les bases, renforcer le calcul mental ou garder l’esprit actif."},
        "faq_page":{"title":"Questions Pitagorin | Âge, sujets, appareils et confidentialité","description":"Réponses sur l’âge, les sujets, les explications, iPhone et iPad, les adultes, la confidentialité, la publicité et Pro.","hero_kicker":"Des réponses claires","hero_title":"Que souhaites-tu savoir ?","hero_text":"Un guide bref sur les élèves, les sujets, l’aide, les appareils, la confidentialité, la publicité et Pro.","questions":[["À quel âge s’adresse Pitagorin ?","Principalement aux enfants de 5 à 13 ans. La difficulté et les thèmes conviennent aussi aux ados et adultes qui révisent."],["Quelles maths peut-on pratiquer ?","Addition, soustraction, multiplication, division, fractions, décimaux, pourcentages, puissances, racines, tables, équations, rapports et fonctions."],["Pitagorin explique-t-elle les méthodes ?","Oui. Le mode Apprentissage propose aides visuelles et méthodes posées ; Algèbre guide la résolution pas à pas."],["Quels appareils sont compatibles ?","iPhone et iPad sous iOS 18 ou iPadOS 18, ou version ultérieure."],["Les ados et adultes peuvent-ils l’utiliser ?","Oui. De courtes séances permettent de réviser et de garder l’esprit actif."],["Faut-il un compte ?","Non. Aucun nom ni e-mail n’est requis ; les progrès restent sur l’appareil."],["Pitagorin est-elle gratuite ?","Le téléchargement est gratuit. Des fonctions Pro facultatives sont proposées par achat intégré."],["Y a-t-il de la publicité ?","La version gratuite peut afficher occasionnellement des publicités interstitielles. Pro est sans publicité."]],"cta_kicker":"Tu explores encore ?","cta_title":"Découvre l’apprentissage.","cta_text":"Compare les modes, parcours les vraies interfaces ou lis le guide des familles."},
        "privacy_page":{"title":"Confidentialité Pitagorin | Des pratiques claires","description":"Comment Pitagorin gère les données locales, photos facultatives, publicités, analyses, achats et la confidentialité des enfants.","hero_kicker":"La confidentialité sans énigme","hero_title":"Politique de confidentialité de Pitagorin","hero_text":"En bref : aucun compte n’est requis, les données d’apprentissage restent sur l’appareil et Pitagorin ne demande ni nom ni e-mail.","updated":"Dernière mise à jour :","date":"3 septembre 2026 · Développeur : Lorenzo Villarroel Perez","on_page":"Sur cette page","nav":[["on-device","Données sur l’appareil"],["services","Publicité et analyse"],["photos","Photos et achats"],["children","Enfants et familles"],["choices","Tes choix"]],"summary":[["Aucun compte","Ni nom ni e-mail requis"],["Progrès locaux","Les données restent sur l’appareil"],["Pro sans publicité","Aucune publicité pour Pro"]],"sections":[["on-device","Ce qui reste sur ton appareil",["Pitagorin conserve localement réglages, progrès, scores, records, maîtrise des tables, historique de l’Académie et photos facultatives du travail écrit. Ces données ne sont pas envoyées à ses propres serveurs ; les sauvegardes gérées par Apple peuvent s’appliquer.","Supprime l’app pour retirer les données locales. Aucun compte n’est requis."]],["services","Publicité et analyse du produit",["Ce site statique ne comporte ni connexion, ni formulaire, ni publicité, ni analyse, ni cookie Pitagorin.","L’app gratuite peut afficher occasionnellement des publicités interstitielles via Google Mobile Ads. Pro est sans publicité. Les annonces sont adaptées aux enfants, classées tout public et non personnalisées. Refuser le suivi n’empêche pas d’apprendre.","Firebase Analytics mesure l’utilisation globale des sections et modes. Noms, comptes, réponses, équations, scores, progrès, identifiants d’achat ou publicitaires, localisation précise et photos sont exclus."]],["photos","Photos et achats",["L’accès à l’appareil photo ou à la photothèque n’est demandé que pour joindre un travail écrit à un examen de l’Académie. La photo reste dans l’historique local.","Apple traite les paiements Pro via l’App Store et StoreKit. Pitagorin reçoit l’état d’achat nécessaire, pas les données de carte ou bancaires."]],["children","Enfants, familles et adultes",["Pitagorin est conçue pour les enfants et les familles et convient aussi aux ados et adultes. Elle ne demande pas aux enfants de créer un compte ou de fournir des coordonnées. Les parents devraient vérifier avec eux les réglages de l’appareil, de l’App Store, de publicité et de sauvegarde."]],["choices","Tes choix et tes questions",["Tu peux refuser le suivi, ne pas joindre de photos et supprimer l’app pour effacer les données locales. Utilise le contact du développeur sur l’App Store pour toute question.","Cette page sera mise à jour si les pratiques de Pitagorin évoluent."]]]}
    },
    "it": {
        "common":{"skip":"Vai al contenuto","primary":"Navigazione principale","home":"Home di Pitagorin","features":"Funzioni","screenshots":"L’app","families":"Per le famiglie","faq":"Domande","privacy":"Privacy","get":"Scarica","menu":"Menu","terms":"Condizioni","footer_nav":"Navigazione a piè di pagina","footer":"Esercizio matematico giocoso e guidato per bambini, famiglie e chiunque voglia continuare a imparare.","available":"Pitagorin. Disponibile sull’App Store.","store":"Apri l’App Store","all_features":"Scopri tutte le funzioni"},
        "index":{"title":"Pitagorin: app di matematica | Giochi, tabelline e algebra","description":"Acquisisci sicurezza con giochi di calcolo, tabelline, spiegazioni visive e algebra guidata su iPhone e iPad. Per bambini dai 5 ai 13 anni e adulti.","og":"Pitagorin: esercitarsi in matematica giocando","hero_kicker":"La matematica che invita a iniziare","hero_title":"Comprendi. Esercitati. Falla tua.","hero_text":"Pitagorin trasforma aritmetica, tabelline e primi passi nell’algebra in sessioni brevi con spiegazioni chiare. È pensata per bambini dai 5 ai 13 anni ed è utile anche agli adulti che vogliono ripassare la matematica quotidiana.","download":"Scarica gratis dall’App Store","explore":"Scopri le modalità di apprendimento","device":"Disponibile per iPhone e iPad","proof":[["Dai 5 ai 13 anni","Basi adatte all’età"],["Anche per adulti","Ripassi rapidi"],["iPhone + iPad","iOS 18 o successivo"],["Download gratuito","Funzioni Pro facoltative"]],"why_kicker":"Un ciclo di apprendimento migliore","why_title":"Esercitati con uno scopo.","why_text":"Ogni modalità ha un obiettivo chiaro: sviluppare fluidità, comprendere un metodo o allenare il ragionamento.","benefits":[["Gioca per diventare più fluido","Sfida Velocità, Modalità Sopravvivenza, Sfida di velocità a duello e le sfide rendono dinamica la ripetizione."],["Fermati per capire","Gli aiuti visivi e i procedimenti scritti mostrano ogni passaggio dell’aritmetica e dell’algebra."],["Torna con un obiettivo","Record personali, padronanza delle tabelline e storico dell’Accademia indicano cosa esercitare."]],"screens_kicker":"Guarda l’app reale","screens_title":"Quattro modi per acquisire sicurezza.","screens_text":"Da un minuto di calcolo mentale a un’equazione guidata, il punto di partenza è chiaro e il riscontro immediato.","screen_captions":[["Sfida il tempo","Sviluppa la fluidità di calcolo"],["Impara al tuo ritmo","Consulta un metodo visivo"],["Impara le tabelline","Esercitati da 1 a 12"],["Risolvi passo passo","Comprendi le basi dell’algebra"]],"view_screens":"Vedi tutte le schermate","compare":"Confronta le funzioni","audience_kicker":"Un’app, obiettivi diversi","audience_title":"La voglia di imparare continua a crescere.","audience_text":"La modalità tranquilla e le sfide vivaci sono adatte al primo incontro con un concetto, al rinforzo scolastico o all’allenamento mentale quotidiano.","audiences":[["Bambini e famiglie","Costruisci le basi senza paura.","Scegli operazioni e difficoltà adatte all’età e apri una spiegazione visiva quando serve.","Leggi la guida per famiglie"],["Ragazzi e adulti","Mantieni agile la matematica quotidiana.","Ripassa aritmetica, percentuali, frazioni, radici, tabelline o algebra in sessioni brevi.","Trova una modalità"]],"cta_kicker":"Quando vuoi","cta_title":"Dai valore ai prossimi cinque minuti.","cta_text":"Scarica Pitagorin gratis per iPhone e iPad. Le funzioni Pro facoltative sono disponibili tramite acquisti in-app."},
        "features":{"title":"Funzioni di Pitagorin | Aritmetica, tabelline e algebra","description":"Scopri giochi aritmetici, modalità Studio, tabelline, Accademia, sfide e algebra guidata in Pitagorin.","hero_kicker":"Dentro Pitagorin","hero_title":"Sei percorsi. Un obiettivo chiaro.","hero_text":"Scegli un gioco rapido, una spiegazione tranquilla, le tabelline, una verifica personalizzata, una sfida di ragionamento o l’algebra guidata.","compare":"Confronta le modalità","real":"Guarda l’app reale","modes_kicker":"Scegli il tuo percorso","modes_title":"Una modalità per ogni tipo di esercizio.","modes_text":"Ogni funzione risponde a un’esigenza distinta con intensità, argomento e supporto a scelta.","modes":[["Fluidità","Giochi aritmetici","Esercitati con addizione, sottrazione, moltiplicazione, divisione, frazioni, decimali, percentuali, potenze, radici e altro in tre livelli."],["Comprensione","Modalità Studio","Lavora senza tempo, inserisci la risposta e apri aiuti visivi specifici per ogni operazione."],["Memoria","Tabelline","Impara le tabelline da 1 a 12. Pitagorin Pro aggiunge Ripasso intelligente e Sprint di scioltezza."],["Esercizio autonomo","L’Accademia","Crea una verifica scegliendo operazioni e difficoltà, salva il risultato e rivedi le spiegazioni."],["Ragionamento","Giochi matematici","Raggiungi un numero obiettivo o bilancia i due membri di un’equazione con suggerimenti e annulla."],["Passo successivo","Algebra guidata","Segui basi, equazioni, proporzioni, relazioni lineari, sistemi, esponenti e funzioni."]],"loop_kicker":"Il ciclo di apprendimento","loop_title":"Prova. Comprendi. Riprova.","loop_text":"Il riscontro rapido mantiene il ritmo e le spiegazioni creano vera comprensione.","loop":["Scegli operazione, tabellina, argomento o sfida","Regola la difficoltà","Usa un aiuto visivo quando serve","Torna ai progressi e ai record"],"calm":"Impara con calma","calm_sub":"Senza tempo e con supporto","reason":"Ragiona con chiarezza","reason_sub":"Guida passo passo","path_kicker":"Come funziona una sessione","path_title":"Un percorso semplice nella matematica.","path_text":"Il passaggio successivo resta chiaro per un bambino autonomo o un adulto che riprende la matematica.","path":[["Scegli","Seleziona un argomento o gioco per l’obiettivo di oggi."],["Prova","Lavora a un livello e ritmo confortevoli."],["Comprendi","Apri un suggerimento o una spiegazione se serve."],["Torna","Consolida la padronanza o supera il record."]],"cta_kicker":"Inizia a esercitarti","cta_title":"Trova la modalità giusta per te.","cta_text":"Pitagorin si scarica gratis su iPhone e iPad, con funzioni Pro facoltative nell’app."},
        "screenshots":{"title":"Schermate di Pitagorin | Giochi e apprendimento guidato","description":"Guarda schermate reali di Pitagorin per calcolo rapido, apprendimento tranquillo, tabelline e algebra passo passo.","hero_kicker":"L’esperienza reale","hero_title":"Chiara per imparare. Vivace per tornare.","hero_text":"Queste sono schermate reali di Pitagorin. Ognuna unisce un compito matematico preciso a segnali visivi invitanti e a un’azione successiva chiara.","gallery_kicker":"Quattro momenti di apprendimento","gallery_title":"Dal richiamo rapido al ragionamento guidato.","gallery_text":"L’interfaccia cambia con l’obiettivo: dinamica nelle sfide, tranquilla per imparare ed esplicita nell’algebra.","captions":[["Sfida Velocità","Calcolo mentale breve e dinamico"],["Modalità Studio","Esercizio senza tempo con aiuti visivi"],["Tabelline","Richiamo mirato delle tabelline da 1 a 12"],["Algebra guidata","Ragiona sulle equazioni passo passo"]],"focus_kicker":"Progettata per concentrarsi","focus_title":"Anche la decorazione ha uno scopo.","focus_text":"Il colore invita all’attività, mentre l’area di lavoro resta spaziosa e leggibile.","focus":[["Domande leggibili","Espressioni grandi e spazi generosi rendono facile individuare il compito."],["Scelte chiare","Ogni schermata limita le azioni concorrenti e rende evidente il passo successivo."],["Aiuto quando serve","Il supporto appare quando è utile senza interrompere ogni tentativo."],["Progressi visibili","Punteggi, tempo, padronanza e storico danno una direzione concreta."]],"cta_kicker":"Fai il passo successivo","cta_title":"Prova l’esperienza reale.","cta_text":"Scarica Pitagorin gratis su iPhone o iPad, oppure scopri prima tutte le modalità.","explore":"Scopri le funzioni"},
        "parents":{"title":"Pitagorin per le famiglie | Matematica dai 5 ai 13 anni","description":"Scopri come Pitagorin aiuta i bambini dai 5 ai 13 anni con difficoltà adatta, spiegazioni visive, tabelline, progressi e algebra.","hero_kicker":"Per i bambini e gli adulti al loro fianco","hero_title":"La sicurezza nasce quando il metodo ha senso.","hero_text":"Pitagorin aiuta i bambini dai 5 ai 13 anni a esercitarsi in autonomia, scegliere una sfida adatta e aprire una spiegazione visiva quando serve.","download":"Scarica Pitagorin gratis","expect_link":"Cosa possono aspettarsi le famiglie","expect_kicker":"Un equilibrio attento","expect_title":"Autonomia con l’aiuto a portata di mano.","expect_text":"I bambini fanno scelte significative senza dover indovinare il passo successivo. L’obiettivo è esercitarsi con uno scopo, non accumulare tempo sullo schermo.","expect":[["Inizia al livello giusto","Operazioni adatte all’età e tre difficoltà offrono una sfida gestibile."],["Guarda come funziona","I procedimenti scritti spiegano riporti, prestiti, frazioni, radici, priorità e altre basi."],["Nota i progressi reali","Record, padronanza delle tabelline, storico dell’Accademia e punteggi rendono visibile il miglioramento."]],"practice_kicker":"Cosa possono esercitare","practice_title":"Dai primi calcoli all’algebra.","practice_text":"Possono seguire l’argomento scolastico di oggi o la propria curiosità.","practice":["Addizione, sottrazione, moltiplicazione e divisione","Frazioni, decimali, percentuali, potenze e radici","Tabelline da 1 a 12","Equazioni, rapporti, funzioni e relazioni lineari","Sfide numeriche e giochi di bilanciamento"],"care_kicker":"Buono a sapersi","care_title":"Progettata con cura.","care_text":"Pitagorin si scarica gratis con funzioni Pro facoltative. Non serve un account e i progressi restano sul dispositivo.","care":[["Nessun account","Non vengono richiesti nome, email o profilo per iniziare."],["Dati di apprendimento locali","Progressi, punteggi, padronanza e foto facoltative restano sul dispositivo."],["Accessibilità considerata","Testo più grande, modalità scura, movimento ridotto e descrizioni VoiceOver sono supportati."],["Privacy chiara","La breve informativa spiega annunci, analisi, acquisti e foto."]],"cta_kicker":"Per ogni mente che cresce","cta_title":"I bambini guidano il design. Tutti possono esercitarsi.","cta_text":"Ragazzi e adulti possono ripassare le basi, rafforzare il calcolo mentale o mantenere la mente attiva."},
        "faq_page":{"title":"Domande su Pitagorin | Età, argomenti, dispositivi e privacy","description":"Risposte su età, matematica, spiegazioni, iPhone e iPad, adulti, privacy, annunci e Pitagorin Pro.","hero_kicker":"Risposte chiare","hero_title":"Cosa vuoi sapere?","hero_text":"Una guida breve su utenti, argomenti, supporto, dispositivi, privacy, pubblicità e Pro.","questions":[["Per quale età è Pitagorin?","È pensata soprattutto per bambini dai 5 ai 13 anni. Difficoltà e argomenti sono utili anche a ragazzi e adulti."],["Quale matematica si può esercitare?","Addizione, sottrazione, moltiplicazione, divisione, frazioni, decimali, percentuali, potenze, radici, tabelline, equazioni, rapporti e funzioni."],["Pitagorin spiega come risolvere un problema?","Sì. Apprendimento offre aiuti visivi e procedimenti scritti; Algebra guida la risoluzione passo passo."],["Quali dispositivi supporta?","iPhone e iPad con iOS 18 o iPadOS 18, o versioni successive."],["Ragazzi e adulti possono usarla?","Sì. Sessioni brevi aiutano a ripassare e mantenere la mente attiva."],["Serve un account?","No. Non servono nome o email; i progressi restano sul dispositivo."],["Pitagorin è gratuita?","Il download è gratuito. Le funzioni Pro facoltative sono disponibili con acquisti in-app."],["Pitagorin mostra pubblicità?","La versione gratuita può mostrare occasionalmente annunci interstiziali. Pro non mostra annunci."]],"cta_kicker":"Vuoi scoprire altro?","cta_title":"Guarda come si impara.","cta_text":"Confronta le modalità, esplora schermate reali o leggi la guida per famiglie."},
        "privacy_page":{"title":"Privacy di Pitagorin | Pratiche chiare sui dati","description":"Come Pitagorin gestisce dati locali, foto facoltative, pubblicità, analisi, acquisti e privacy dei bambini.","hero_kicker":"Privacy senza enigmi","hero_title":"Informativa sulla privacy di Pitagorin","hero_text":"In breve: non serve un account, i dati di apprendimento restano sul dispositivo e Pitagorin non chiede nome o email.","updated":"Ultimo aggiornamento:","date":"3 settembre 2026 · Sviluppatore: Lorenzo Villarroel Perez","on_page":"In questa pagina","nav":[["on-device","Dati sul dispositivo"],["services","Pubblicità e analisi"],["photos","Foto e acquisti"],["children","Bambini e famiglie"],["choices","Le tue scelte"]],"summary":[["Nessun account","Nome ed email non necessari"],["Progressi locali","I dati restano sul dispositivo"],["Pro senza annunci","Nessuna pubblicità per Pro"]],"sections":[["on-device","Cosa rimane sul dispositivo",["Pitagorin salva localmente impostazioni, progressi, punteggi, record, padronanza delle tabelline, storico dell’Accademia e foto facoltative del lavoro scritto. Non carica questi dati su server propri; possono essere applicati i backup gestiti da Apple.","Puoi rimuovere i dati locali eliminando l’app. Non serve un account."]],["services","Pubblicità e analisi del prodotto",["Questo sito statico non ha accesso, modulo di contatto, pubblicità, analisi o cookie di Pitagorin.","L’app gratuita può mostrare occasionalmente annunci interstiziali tramite Google Mobile Ads. Pro è senza annunci. La pubblicità è configurata per bambini, con classificazione generale e senza personalizzazione. Rifiutare il tracciamento non impedisce di imparare.","Firebase Analytics misura l’uso aggregato di aree e modalità. Esclude nomi, account, risposte, equazioni, punteggi, progressi, ID di acquisto o pubblicitari, posizione precisa e foto."]],["photos","Foto e acquisti",["Fotocamera o libreria vengono richieste solo se scegli di allegare un lavoro scritto a una verifica dell’Accademia. La foto resta nello storico locale.","Apple gestisce i pagamenti Pro tramite App Store e StoreKit. Pitagorin riceve lo stato necessario a sbloccare Pro, non i dati della carta o bancari."]],["children","Bambini, famiglie e adulti",["Pitagorin è progettata per bambini e famiglie ed è adatta anche a ragazzi e adulti. Non chiede ai bambini di creare un account o fornire contatti. Genitori e tutori dovrebbero rivedere con loro le impostazioni di dispositivo, App Store, pubblicità e backup."]],["choices","Le tue scelte e domande",["Puoi rifiutare il tracciamento, non allegare foto ed eliminare l’app per rimuovere i dati locali. Per domande sulla privacy usa il contatto dello sviluppatore nell’App Store.","Questa pagina verrà aggiornata se cambiano le pratiche di Pitagorin."]]]}
    },
}


def esc(value: str) -> str:
    return html.escape(value, quote=True)


def localized_url(locale: str, page: str) -> str:
    filename = "" if page == "index" else f"{page}.html"
    return f"{BASE_URL}/{locale}/{filename}"


def alternates(page: str) -> str:
    filename = "" if page == "index" else f"{page}.html"
    lines = [f'  <link rel="alternate" hreflang="en" href="{BASE_URL}/{filename}">']
    lines += [f'  <link rel="alternate" hreflang="{lang}" href="{BASE_URL}/{lang}/{filename}">' for lang in ("es", "de", "fr", "it")]
    lines.append(f'  <link rel="alternate" hreflang="x-default" href="{BASE_URL}/{filename}">')
    return "\n".join(lines)


def header(locale: str, current: str, c: dict[str, str]) -> str:
    def link(page: str, label: str) -> str:
        active = ' aria-current="page"' if page == current else ""
        return f'<a{active} href="{page}.html">{esc(label)}</a>'
    nav = "".join((link("features", c["features"]), link("screenshots", c["screenshots"]), link("parents", c["families"]), link("faq", c["faq"])))
    mobile = nav + link("privacy", c["privacy"])
    store = f'https://apps.apple.com/{LANGUAGES[locale]["store"]}/app/pitagorin/id{APP_ID}'
    return f'''<a class="skip-link" href="#main">{esc(c["skip"])}</a>
  <header class="site-header"><nav class="nav" aria-label="{esc(c["primary"])}">
    <a class="brand" href="index.html" aria-label="{esc(c["home"])}"><span class="brand-mark"><img src="../assets/app-icon.png" width="44" height="44" alt=""></span><span>Pitagorin</span></a>
    <div class="nav-links">{nav}<a class="nav-cta" href="{store}">{esc(c["get"])}</a></div>
    <details class="nav-menu"><summary>{esc(c["menu"])}</summary><div class="nav-menu-panel">{mobile}<a href="{store}">{esc(c["get"])}</a></div></details>
  </nav></header>'''


def footer(c: dict[str, str]) -> str:
    links = (("features", c["features"]), ("screenshots", c["screenshots"]), ("parents", c["families"]), ("faq", c["faq"]), ("privacy", c["privacy"]))
    nav = "".join(f'<a href="{page}.html">{esc(label)}</a>' for page, label in links)
    return f'''<footer class="site-footer"><div class="footer-inner"><div><a class="brand" href="index.html"><span class="brand-mark"><img src="../assets/app-icon.png" width="44" height="44" alt=""></span><span>Pitagorin</span></a><p class="footer-copy">{esc(c["footer"])}</p></div><nav class="footer-links" aria-label="{esc(c["footer_nav"])}">{nav}<a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">{esc(c["terms"])}</a></nav></div><p class="footer-bottom">© <span data-year></span> {esc(c["available"])}</p></footer>'''


def document(locale: str, page: str, title: str, description: str, body: str, *, og_image: str = "01_speed_challenge", schema_type: str = "WebPage", schema_extra: dict | None = None) -> str:
    c = COPY[locale]["common"]
    url = localized_url(locale, page)
    schema = {"@context": "https://schema.org", "@type": schema_type, "name": title.split("|")[0].strip(), "description": description, "url": url, "inLanguage": locale, "isPartOf": {"@id": f"{BASE_URL}/#website"}, "about": {"@id": f"{BASE_URL}/#app"}}
    if schema_extra:
        schema.update(schema_extra)
    image_url = f"{BASE_URL}/assets/screenshots/{locale}/{og_image}.jpg" if og_image != "app-icon" else f"{BASE_URL}/assets/app-icon.png"
    return f'''<!doctype html>
<html lang="{locale}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(title)}</title>
  <meta name="description" content="{esc(description)}">
  <meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1">
  <meta name="apple-itunes-app" content="app-id={APP_ID}">
  <link rel="canonical" href="{url}">
{alternates(page)}
  <meta property="og:title" content="{esc(title.split('|')[0].strip())}">
  <meta property="og:description" content="{esc(description)}">
  <meta property="og:type" content="{'article' if page == 'privacy' else 'website'}">
  <meta property="og:url" content="{url}">
  <meta property="og:locale" content="{locale}_{locale.upper()}">
  <meta property="og:image" content="{image_url}">
  <meta property="og:image:alt" content="{esc(title.split('|')[0].strip())}">
  <meta name="twitter:card" content="{'summary' if page == 'privacy' else 'summary_large_image'}">
  <meta name="theme-color" content="#101a3a">
  <link rel="icon" href="../assets/app-icon.png" type="image/png">
  <link rel="stylesheet" href="../styles.css">
  <script type="application/ld+json">{json.dumps(schema, ensure_ascii=False, separators=(',', ':'))}</script>
</head>
<body data-locale="{locale}" data-page="{page}">
  {header(locale, page, c)}
  <main id="main">{body}</main>
  {footer(c)}
  <script src="../script.js"></script>
</body>
</html>
'''


def phone(locale: str, image: str, alt: str, *, lazy: bool = False) -> str:
    loading = ' loading="lazy"' if lazy else ""
    return f'<div class="phone"><img src="../assets/screenshots/{locale}/{image}.jpg" width="736" height="1600"{loading} alt="{esc(alt)}"></div>'


def screen(locale: str, image: str, title: str, subtitle: str, alt: str, *, lazy: bool = True) -> str:
    loading = ' loading="lazy"' if lazy else ""
    return f'<figure class="screen-card"><div class="screen-frame"><img src="../assets/screenshots/{locale}/{image}.jpg" width="736" height="1600"{loading} alt="{esc(alt)}"></div><figcaption><strong>{esc(title)}</strong><span>{esc(subtitle)}</span></figcaption></figure>'


def render_index(locale: str, d: dict, c: dict) -> str:
    proof = "".join(f'<div class="proof-item"><strong>{esc(a)}</strong><span>{esc(b)}</span></div>' for a, b in d["proof"])
    benefits = "".join(f'<article class="card"><div class="number-badge" aria-hidden="true">0{i}</div><h3>{esc(a)}</h3><p>{esc(b)}</p></article>' for i, (a, b) in enumerate(d["benefits"], 1))
    images = ("01_speed_challenge", "03_learning_mode", "05_times_tables_learning", "07_algebra_guided_solving")
    screens = "".join(screen(locale, image, a, b, f"{a}: {b}", lazy=True) for image, (a, b) in zip(images, d["screen_captions"]))
    audiences = "".join(f'<article class="card audience-card"><span class="tag">{esc(tag)}</span><h3>{esc(title)}</h3><p>{esc(text)}</p><div class="actions"><a class="button {"button-primary" if i == 0 else "button-dark"}" href="{"parents.html" if i == 0 else "features.html"}">{esc(action)}</a></div></article>' for i, (tag, title, text, action) in enumerate(d["audiences"]))
    return f'''<div class="hero-shell"><section class="hero"><div class="hero-copy"><p class="eyebrow">{esc(d["hero_kicker"])}</p><h1>{esc(d["hero_title"])}</h1><p class="lede">{esc(d["hero_text"])}</p><div class="actions"><a class="button button-primary" href="https://apps.apple.com/{LANGUAGES[locale]["store"]}/app/pitagorin/id{APP_ID}">{esc(d["download"])}</a><a class="button button-ghost" href="features.html">{esc(d["explore"])}</a></div><p class="hero-note">{esc(d["device"])}</p></div><div class="hero-visual" aria-label="Pitagorin"><div class="hero-orbit" aria-hidden="true"></div><div class="phone hero-phone-side"><img src="../assets/screenshots/{locale}/07_algebra_guided_solving.jpg" width="736" height="1600" alt="Pitagorin"></div><div class="phone hero-phone-main"><img src="../assets/screenshots/{locale}/01_speed_challenge.jpg" width="736" height="1600" alt="Pitagorin"></div><div class="math-chip chip-one" aria-hidden="true">7 × 8</div><div class="math-chip chip-two" aria-hidden="true">✓</div></div></section></div>
<section class="proof-bar"><div class="proof-bar-inner">{proof}</div></section>
<section class="section"><div class="section-heading"><div><p class="eyebrow">{esc(d["why_kicker"])}</p><h2>{esc(d["why_title"])}</h2></div><p>{esc(d["why_text"])}</p></div><div class="grid">{benefits}</div></section>
<section class="section tint"><div class="section-heading"><div><p class="eyebrow">{esc(d["screens_kicker"])}</p><h2>{esc(d["screens_title"])}</h2></div><p>{esc(d["screens_text"])}</p></div><div class="screen-story">{screens}</div><div class="actions"><a class="button button-dark" href="screenshots.html">{esc(d["view_screens"])}</a><a class="button button-secondary" href="features.html">{esc(d["compare"])}</a></div></section>
<section class="section"><div class="section-heading"><div><p class="eyebrow">{esc(d["audience_kicker"])}</p><h2>{esc(d["audience_title"])}</h2></div><p>{esc(d["audience_text"])}</p></div><div class="audience-grid">{audiences}</div></section>
<section class="section section-compact mint-section"><div class="cta-panel"><div><p class="eyebrow">{esc(d["cta_kicker"])}</p><h2>{esc(d["cta_title"])}</h2><p>{esc(d["cta_text"])}</p></div><div class="actions"><a class="button button-primary" href="https://apps.apple.com/{LANGUAGES[locale]["store"]}/app/pitagorin/id{APP_ID}">{esc(c["store"])}</a></div></div></section>'''


def render_features(locale: str, d: dict, c: dict) -> str:
    modes = "".join(f'<article class="card feature-card"><span class="tag">{esc(tag)}</span><h3>{esc(title)}</h3><p>{esc(text)}</p></article>' for tag, title, text in d["modes"])
    loop = "".join(f'<li>{esc(item)}</li>' for item in d["loop"])
    path = "".join(f'<div class="path-step"><strong>{esc(a)}</strong><span>{esc(b)}</span></div>' for a, b in d["path"])
    pair = screen(locale, "03_learning_mode", d["calm"], d["calm_sub"], f'{d["calm"]}: {d["calm_sub"]}') + screen(locale, "07_algebra_guided_solving", d["reason"], d["reason_sub"], f'{d["reason"]}: {d["reason_sub"]}')
    return f'''<div class="dark-hero"><section class="page-hero hero-inline-shot"><div><p class="eyebrow">{esc(d["hero_kicker"])}</p><h1>{esc(d["hero_title"])}</h1><p class="lede">{esc(d["hero_text"])}</p><div class="actions"><a class="button button-primary" href="#modes">{esc(d["compare"])}</a><a class="button button-ghost" href="screenshots.html">{esc(d["real"])}</a></div></div>{phone(locale, "01_speed_challenge", "Pitagorin")}</section></div>
<section class="section" id="modes"><div class="section-heading"><div><p class="eyebrow">{esc(d["modes_kicker"])}</p><h2>{esc(d["modes_title"])}</h2></div><p>{esc(d["modes_text"])}</p></div><div class="feature-list">{modes}</div></section>
<section class="section tint"><div class="split"><div><p class="eyebrow">{esc(d["loop_kicker"])}</p><h2>{esc(d["loop_title"])}</h2><p class="lede">{esc(d["loop_text"])}</p><ul class="checklist">{loop}</ul></div><div class="screen-story screen-pair">{pair}</div></div></section>
<section class="section"><div class="section-heading"><div><p class="eyebrow">{esc(d["path_kicker"])}</p><h2>{esc(d["path_title"])}</h2></div><p>{esc(d["path_text"])}</p></div><div class="learning-path">{path}</div></section>
<section class="section section-compact mint-section"><div class="cta-panel"><div><p class="eyebrow">{esc(d["cta_kicker"])}</p><h2>{esc(d["cta_title"])}</h2><p>{esc(d["cta_text"])}</p></div><div class="actions"><a class="button button-primary" href="https://apps.apple.com/{LANGUAGES[locale]["store"]}/app/pitagorin/id{APP_ID}">{esc(c["store"])}</a></div></div></section>'''


def render_screenshots(locale: str, d: dict, c: dict) -> str:
    images = ("01_speed_challenge", "03_learning_mode", "05_times_tables_learning", "07_algebra_guided_solving")
    screens = "".join(screen(locale, image, a, b, f"{a}: {b}", lazy=i > 0) for i, (image, (a, b)) in enumerate(zip(images, d["captions"])))
    focus = "".join(f'<div class="trust-item"><strong>{esc(a)}</strong><p>{esc(b)}</p></div>' for a, b in d["focus"])
    return f'''<div class="dark-hero"><section class="page-hero"><p class="eyebrow">{esc(d["hero_kicker"])}</p><h1>{esc(d["hero_title"])}</h1><p class="lede">{esc(d["hero_text"])}</p></section></div>
<section class="section"><div class="section-heading"><div><p class="eyebrow">{esc(d["gallery_kicker"])}</p><h2>{esc(d["gallery_title"])}</h2></div><p>{esc(d["gallery_text"])}</p></div><div class="screen-story">{screens}</div></section>
<section class="section tint"><div class="split"><div><p class="eyebrow">{esc(d["focus_kicker"])}</p><h2>{esc(d["focus_title"])}</h2><p class="lede">{esc(d["focus_text"])}</p></div><div class="trust-list">{focus}</div></div></section>
<section class="section section-compact"><div class="cta-panel"><div><p class="eyebrow">{esc(d["cta_kicker"])}</p><h2>{esc(d["cta_title"])}</h2><p>{esc(d["cta_text"])}</p></div><div class="actions"><a class="button button-primary" href="https://apps.apple.com/{LANGUAGES[locale]["store"]}/app/pitagorin/id{APP_ID}">{esc(c["store"])}</a><a class="button button-ghost" href="features.html">{esc(d["explore"])}</a></div></div></section>'''


def render_parents(locale: str, d: dict, c: dict) -> str:
    cards = "".join(f'<article class="card"><div class="number-badge">0{i}</div><h3>{esc(a)}</h3><p>{esc(b)}</p></article>' for i, (a, b) in enumerate(d["expect"], 1))
    practice = "".join(f'<li>{esc(item)}</li>' for item in d["practice"])
    care = "".join(f'<div class="trust-item"><strong>{esc(a)}</strong><p>{esc(b)}</p></div>' for a, b in d["care"])
    return f'''<div class="dark-hero"><section class="page-hero hero-inline-shot"><div><p class="eyebrow">{esc(d["hero_kicker"])}</p><h1>{esc(d["hero_title"])}</h1><p class="lede">{esc(d["hero_text"])}</p><div class="actions"><a class="button button-primary" href="https://apps.apple.com/{LANGUAGES[locale]["store"]}/app/pitagorin/id{APP_ID}">{esc(d["download"])}</a><a class="button button-ghost" href="#what-to-expect">{esc(d["expect_link"])}</a></div></div>{phone(locale, "03_learning_mode", "Pitagorin")}</section></div>
<section class="section" id="what-to-expect"><div class="section-heading"><div><p class="eyebrow">{esc(d["expect_kicker"])}</p><h2>{esc(d["expect_title"])}</h2></div><p>{esc(d["expect_text"])}</p></div><div class="grid">{cards}</div></section>
<section class="section tint"><div class="split"><div><p class="eyebrow">{esc(d["practice_kicker"])}</p><h2>{esc(d["practice_title"])}</h2><p class="lede">{esc(d["practice_text"])}</p></div><div class="card"><ul class="checklist">{practice}</ul></div></div></section>
<section class="section"><div class="section-heading"><div><p class="eyebrow">{esc(d["care_kicker"])}</p><h2>{esc(d["care_title"])}</h2></div><p>{esc(d["care_text"])}</p></div><div class="trust-list">{care}</div></section>
<section class="section section-compact mint-section"><div class="cta-panel"><div><p class="eyebrow">{esc(d["cta_kicker"])}</p><h2>{esc(d["cta_title"])}</h2><p>{esc(d["cta_text"])}</p></div><div class="actions"><a class="button button-primary" href="features.html">{esc(c["all_features"])}</a></div></div></section>'''


def render_faq(d: dict, c: dict) -> tuple[str, dict]:
    items = "".join(f'<details class="faq-item"{" open" if i == 0 else ""}><summary>{esc(q)}</summary><p>{esc(a)}</p></details>' for i, (q, a) in enumerate(d["questions"]))
    schema = {"mainEntity": [{"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in d["questions"]]}
    body = f'''<div class="dark-hero"><section class="page-hero"><p class="eyebrow">{esc(d["hero_kicker"])}</p><h1>{esc(d["hero_title"])}</h1><p class="lede">{esc(d["hero_text"])}</p></section></div><section class="section"><div class="faq-list">{items}</div></section><section class="section section-compact mint-section"><div class="cta-panel"><div><p class="eyebrow">{esc(d["cta_kicker"])}</p><h2>{esc(d["cta_title"])}</h2><p>{esc(d["cta_text"])}</p></div><div class="actions"><a class="button button-primary" href="features.html">{esc(c["features"])}</a><a class="button button-ghost" href="parents.html">{esc(c["families"])}</a></div></div></section>'''
    return body, schema


def render_privacy(d: dict) -> str:
    nav = "".join(f'<a href="#{ident}">{esc(label)}</a>' for ident, label in d["nav"])
    summary = "".join(f'<div><strong>{esc(a)}</strong><span>{esc(b)}</span></div>' for a, b in d["summary"])
    sections = "".join(f'<section class="policy-section" id="{ident}"><h2>{esc(title)}</h2>{"".join(f"<p>{esc(p)}</p>" for p in paragraphs)}</section>' for ident, title, paragraphs in d["sections"])
    return f'''<div class="dark-hero"><section class="page-hero"><p class="eyebrow">{esc(d["hero_kicker"])}</p><h1>{esc(d["hero_title"])}</h1><p class="lede">{esc(d["hero_text"])}</p><p class="policy-meta"><strong>{esc(d["updated"])}</strong> {esc(d["date"])}</p></section></div><section class="section policy-layout"><nav class="policy-nav"><strong>{esc(d["on_page"])}</strong>{nav}</nav><div><div class="policy-summary">{summary}</div>{sections}</div></section>'''


def build_locale(locale: str) -> None:
    data = COPY[locale]
    c = data["common"]
    destination = SITE / locale
    destination.mkdir(parents=True, exist_ok=True)
    renderers = {
        "index": lambda d: render_index(locale, d, c),
        "features": lambda d: render_features(locale, d, c),
        "screenshots": lambda d: render_screenshots(locale, d, c),
        "parents": lambda d: render_parents(locale, d, c),
    }
    for page in ("index", "features", "screenshots", "parents"):
        d = data[page]
        output = document(locale, page, d["title"], d["description"], renderers[page](d), og_image="03_learning_mode" if page == "parents" else ("05_times_tables_learning" if page == "screenshots" else "01_speed_challenge"))
        (destination / f"{page}.html").write_text(output, encoding="utf-8")
    d = data["faq_page"]
    body, schema = render_faq(d, c)
    (destination / "faq.html").write_text(document(locale, "faq", d["title"], d["description"], body, schema_type="FAQPage", schema_extra=schema), encoding="utf-8")
    d = data["privacy_page"]
    (destination / "privacy.html").write_text(document(locale, "privacy", d["title"], d["description"], render_privacy(d), og_image="app-icon"), encoding="utf-8")


def write_sitemap() -> None:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    ]
    for page in PAGES:
        filename = "" if page == "index" else f"{page}.html"
        urls = {"en": f"{BASE_URL}/{filename}"}
        urls.update({locale: f"{BASE_URL}/{locale}/{filename}" for locale in ("es", "de", "fr", "it")})
        for locale, url in urls.items():
            alternates_xml = "".join(
                f'<xhtml:link rel="alternate" hreflang="{code}" href="{target}"/>'
                for code, target in urls.items()
            )
            alternates_xml += f'<xhtml:link rel="alternate" hreflang="x-default" href="{urls["en"]}"/>'
            lines.append(f'  <url><loc>{url}</loc><lastmod>2026-09-03</lastmod>{alternates_xml}</url>')
    lines.append('</urlset>')
    (SITE / "sitemap.xml").write_text("\n".join(lines) + "\n", encoding="utf-8")


def validate_app_terms() -> None:
    for locale, expected_terms in APP_TERMS.items():
        localized_copy = json.dumps(COPY[locale], ensure_ascii=False)
        missing = [term for term in expected_terms if term not in localized_copy]
        if missing:
            raise ValueError(f"{locale} website copy is missing app terms: {', '.join(missing)}")


if __name__ == "__main__":
    validate_app_terms()
    for code in COPY:
        build_locale(code)
    write_sitemap()
